### ISSUE TITLE
IP stack

### ISSUE THREAD

**Issue by jgraef** [jgraef/skunk#20]
Parse/encode packets. Provide a virtual network wrapper for raw sockets.

# TODO

- [ ] Ethernet
  - [x] decode
  - [ ] encode: missing: write FCS
- [ ] IPv4
  - [ ] decode: missing: verify checksum
  - [ ] encode: missing: back-fill length, checksum
- [ ] IPv6
- [ ] ARP
  - [x] decode
  - [ ] encode
  - [x] virtual socket
  - [x] resolver
  - [x] request handler 
- [ ] UDP
  - [ ] decode: missing: verify checksum
  - [ ] encode
  - [x] virtual socket
- [ ] TCP
  - [ ] decode: missing: header options
  - [ ] encode
  - [ ] virtual socket
- [ ] ICMP
  - [ ] decode: missing verify checksum
  - [ ] encode

# Notes

- [smoltcp][1] looks good too

[1]: https://docs.rs/smoltcp/latest/smoltcp/wire/index.html
