### ISSUE TITLE
SOCKS

### ISSUE THREAD

**Issue by jgraef** [jgraef/skunk#24]
# TODO

- [ ] socks4 client
- [x] socks4 server
- [ ] socks5 client
- [x] socks5 server
- [ ] username/password auth. the subnegotiation isn't implemented. we need this.
- [ ] handle bind/accept, associate properly (we don't need this, but a full socks5 impl would be nice)
- [ ] gssapi auth (we don't need this, but the RFC states that a proper socks implementation must support this)

# Reference

- [SOCKS v4](http://ftp.icm.edu.pl/packages/socks/socks4/SOCKS4.protocol)
- [SOCKS v5](https://datatracker.ietf.org/doc/html/rfc1928)
